import React, { useState, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  ActivityIndicator,
  RefreshControl,
  TouchableOpacity,
  Alert,
  Platform,
} from 'react-native';
import { useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { API_URL } from '../src/config/api';
import { useAppColors } from '@/components/appThemeProvider';

interface ReceiptHistoryItem {
  _id: string;
  storeName?: string;
  totalPrice?: number;
  currency?: string;
  scanDate: string;
  itemCount: number;
  healthSummary: {
    safe: number;
    caution: number;
    avoid: number;
  };
}

export default function ReceiptFeedbackHistory() {
  const col = useAppColors();
  const styles = useMemo(() => createStyles(col), [col]);

  const [historyItems, setHistoryItems] = useState<ReceiptHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const fetchReceipts = async () => {
    try {
      const username = await AsyncStorage.getItem('loggedInUser');
      if (!username) {
        setLoading(false);
        return;
      }

      const res = await fetch(`${API_URL}/api/history/receipts/${username}?t=${Date.now()}`);
      const data = await res.json();

      if (data.success) {
        setHistoryItems(
          data.data.sort((a: any, b: any) => new Date(b.scanDate).getTime() - new Date(a.scanDate).getTime())
        );
      }
    } catch (error) {
      console.error('Error fetching receipts:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      fetchReceipts();
    }, [])
  );

  const generateHtml = () => {
    const rows = historyItems
      .map((item) => {
        const date = new Date(item.scanDate).toLocaleDateString();
        const time = new Date(item.scanDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

        return `
        <tr>
          <td>
            <div class="store-name">${item.storeName || 'Unknown Store'}</div>
            <div class="date">${date} at ${time}</div>
          </td>
          <td style="text-align: center;">${item.itemCount}</td>
          <td>
            <div class="badges">
              <span class="badge safe">Safe: ${item.healthSummary.safe}</span>
              <span class="badge caution">Caution: ${item.healthSummary.caution}</span>
              <span class="badge avoid">Avoid: ${item.healthSummary.avoid}</span>
            </div>
          </td>
        </tr>
      `;
      })
      .join('');

    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
            h1 { text-align: center; color: #0096c7; margin-bottom: 10px; }
            .summary { text-align: center; margin-bottom: 30px; font-size: 14px; color: #666; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #f1f5f9; text-align: left; padding: 12px; border-bottom: 2px solid #e2e8f0; font-size: 12px; text-transform: uppercase; color: #64748b; }
            td { padding: 12px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }
            .store-name { font-weight: bold; font-size: 14px; }
            .date { font-size: 12px; color: #666; margin-top: 4px; }
            .badges { display: flex; flex-direction: column; gap: 4px; font-size: 10px; }
            .badge { padding: 2px 6px; border-radius: 4px; font-weight: bold; width: fit-content; }
            .safe { background-color: #d1fae5; color: #065f46; }
            .caution { background-color: #fef3c7; color: #92400e; }
            .avoid { background-color: #fee2e2; color: #991b1b; }
            .footer { margin-top: 40px; text-align: center; font-size: 10px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <h1>Shopping History Report</h1>
          <div class="summary">Generated on ${new Date().toLocaleDateString()}</div>

          <table>
            <thead>
              <tr>
                <th>Store & Date</th>
                <th style="text-align: center;">Items</th>
                <th>Health Breakdown</th>
              </tr>
            </thead>
            <tbody>
              ${rows}
            </tbody>
          </table>

          <div class="footer">
            Report generated by CartGenie (SW Engineering Final Project) | Total Receipts: ${historyItems.length}
          </div>
        </body>
      </html>
    `;
  };

  const handleExportPDF = async () => {
    if (historyItems.length === 0) {
      Alert.alert('No Data', 'There is no history to export.');
      return;
    }

    setIsGeneratingPdf(true);
    try {
      const html = generateHtml();
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
      console.error('Error generating PDF:', error);
      Alert.alert('Error', 'Failed to generate PDF report.');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleDelete = (itemId: string) => {
    Alert.alert('Delete Receipt', 'Are you sure?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          try {
            const res = await fetch(`${API_URL}/api/history/${itemId}`, { method: 'DELETE' });
            const data = await res.json();
            if (data.success) {
              setHistoryItems((prev) => prev.filter((item) => item._id !== itemId));
            }
          } catch (error) {
            console.error(error);
          }
        },
      },
    ]);
  };

  const renderItem = ({ item }: { item: ReceiptHistoryItem }) => {
    const date = new Date(item.scanDate);

    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <View style={styles.storeContainer}>
            <View style={styles.iconBox}>
              <Ionicons name="receipt-outline" size={20} color="#fff" />
            </View>
            <View>
              <Text style={styles.storeName}>{item.storeName || 'Unknown Store'}</Text>
              <Text style={styles.dateText}>
                {date.toLocaleDateString()} • {date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </Text>
            </View>
          </View>

          <TouchableOpacity onPress={() => handleDelete(item._id)} style={styles.deleteBtn} activeOpacity={0.8}>
            <Ionicons name="trash-outline" size={18} color={col.subtitle} />
          </TouchableOpacity>
        </View>

        <View style={styles.divider} />

        <View style={styles.summaryContainer}>
          <Text style={styles.itemCountText}>{item.itemCount} Items Scanned</Text>

          <View style={styles.healthStats}>
            {item.healthSummary.safe > 0 && (
              <View style={[styles.statBadge, { backgroundColor: 'rgba(16,185,129,0.14)', borderColor: '#10B981' }]}>
                <Text style={[styles.statText, { color: '#10B981' }]}>✓ {item.healthSummary.safe}</Text>
              </View>
            )}

            {item.healthSummary.caution > 0 && (
              <View style={[styles.statBadge, { backgroundColor: 'rgba(245,158,11,0.14)', borderColor: '#F59E0B' }]}>
                <Text style={[styles.statText, { color: '#F59E0B' }]}>! {item.healthSummary.caution}</Text>
              </View>
            )}

            {item.healthSummary.avoid > 0 && (
              <View style={[styles.statBadge, { backgroundColor: 'rgba(239,68,68,0.14)', borderColor: '#EF4444' }]}>
                <Text style={[styles.statText, { color: '#EF4444' }]}>✕ {item.healthSummary.avoid}</Text>
              </View>
            )}
          </View>
        </View>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.headerRow}>
        <Text style={styles.headerTitle}>History</Text>

        <TouchableOpacity
          style={[styles.exportBtn, historyItems.length === 0 && { opacity: 0.5 }]}
          onPress={handleExportPDF}
          disabled={isGeneratingPdf || historyItems.length === 0}
          activeOpacity={0.9}
        >
          {isGeneratingPdf ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <>
              <Ionicons name="share-outline" size={18} color="#fff" />
              <Text style={styles.exportText}>Export PDF</Text>
            </>
          )}
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.centerContainer}>
          <ActivityIndicator size="large" color={col.accent || '#0096c7'} />
        </View>
      ) : (
        <FlatList
          data={historyItems}
          keyExtractor={(item) => item._id}
          renderItem={renderItem}
          contentContainerStyle={styles.listContent}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => {
                setRefreshing(true);
                fetchReceipts();
              }}
              tintColor={col.text}
            />
          }
          ListEmptyComponent={
            <View style={styles.emptyContainer}>
              <Ionicons name="document-text-outline" size={60} color={col.subtitle} />
              <Text style={styles.emptyTitle}>No Receipts</Text>
              <Text style={styles.emptySubtitle}>Receipts you save will appear here.</Text>
            </View>
          }
        />
      )}
    </View>
  );
}

function createStyles(c: ReturnType<typeof useAppColors>) {
  const ACCENT = c.accent || '#0096c7';

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.background },

    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 8,
      backgroundColor: c.card,
      borderBottomWidth: 1,
      borderBottomColor: c.inputBorder,
    },
    headerTitle: { fontSize: 22, fontWeight: '800', color: c.text },

    exportBtn: {
      flexDirection: 'row',
      backgroundColor: ACCENT,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      alignItems: 'center',
      gap: 6,
      ...Platform.select({
        ios: { shadowColor: '#0369A1', shadowOpacity: 0.2, shadowRadius: 6, shadowOffset: { width: 0, height: 4 } },
        android: { elevation: 2 },
      }),
    },
    exportText: { color: '#fff', fontWeight: '700', fontSize: 14 },

    centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    listContent: { padding: 16, paddingBottom: 40 },

    card: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: c.inputBorder,
      ...Platform.select({
        ios: { shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: { width: 0, height: 3 } },
        android: { elevation: 3 },
      }),
    },

    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    storeContainer: { flexDirection: 'row', alignItems: 'center', gap: 12 },

    iconBox: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: '#334155',
      justifyContent: 'center',
      alignItems: 'center',
    },

    storeName: { fontSize: 16, fontWeight: '800', color: c.text },
    dateText: { fontSize: 12, color: c.subtitle, marginTop: 2 },

    deleteBtn: { padding: 4 },

    divider: { height: 1, backgroundColor: c.inputBorder, marginBottom: 12 },

    summaryContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    itemCountText: { fontSize: 13, color: c.subtitle, fontWeight: '600' },

    healthStats: { flexDirection: 'row', gap: 8 },
    statBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      borderWidth: 1,
    },
    statText: { fontSize: 12, fontWeight: '800' },

    emptyContainer: { alignItems: 'center', marginTop: 80, paddingHorizontal: 20 },
    emptyTitle: { fontSize: 18, fontWeight: '800', color: c.text, marginTop: 16 },
    emptySubtitle: { fontSize: 14, color: c.subtitle, textAlign: 'center', marginTop: 8 },
  });
}
