import React, { useEffect, useState, useCallback } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  FlatList, 
  ActivityIndicator, 
  RefreshControl, 
  TouchableOpacity,
  Alert,
  Share // אפשר להשתמש גם ב-expo-sharing
} from 'react-native';
import { useRouter, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Print from 'expo-print'; // 📌 ייבוא להדפסה
import * as Sharing from 'expo-sharing'; // 📌 ייבוא לשיתוף
import { API_URL } from '../src/config/api';

interface ReceiptHistoryItem {
  _id: string;
  storeName?: string;
  totalPrice?: number;
  currency?: string;
  scanDate: string;
  itemCount: number;
  healthSummary: {
    safe: number;
    caution: number;
    avoid: number;
  };
}

export default function ReceiptFeedbackHistory() {
  const router = useRouter();
  const [historyItems, setHistoryItems] = useState<ReceiptHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false); // 📌 מצב טעינה ל-PDF

  const fetchReceipts = async () => {
    try {
      const username = await AsyncStorage.getItem('loggedInUser');
      if (!username) {
        setLoading(false);
        return;
      }
      // הוספתי sort כדי שהכי חדש יהיה למעלה
      const res = await fetch(`${API_URL}/api/history/receipts/${username}?t=${Date.now()}`);
      const data = await res.json();

      if (data.success) {
        setHistoryItems(data.data.sort((a: any, b: any) => new Date(b.scanDate).getTime() - new Date(a.scanDate).getTime()));
      }
    } catch (error) {
      console.error('Error fetching receipts:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      fetchReceipts();
    }, [])
  );

  // 📌 פונקציה ליצירת HTML עבור ה-PDF
  const generateHtml = () => {
    const rows = historyItems.map(item => {
      const date = new Date(item.scanDate).toLocaleDateString();
      const time = new Date(item.scanDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      
      return `
        <tr>
          <td>
            <div class="store-name">${item.storeName || 'Unknown Store'}</div>
            <div class="date">${date} at ${time}</div>
          </td>
          <td style="text-align: center;">${item.itemCount}</td>
          <td>
            <div class="badges">
              <span class="badge safe">Safe: ${item.healthSummary.safe}</span>
              <span class="badge caution">Caution: ${item.healthSummary.caution}</span>
              <span class="badge avoid">Avoid: ${item.healthSummary.avoid}</span>
            </div>
          </td>
        </tr>
      `;
    }).join('');

    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
            h1 { text-align: center; color: #0096c7; margin-bottom: 10px; }
            .summary { text-align: center; margin-bottom: 30px; font-size: 14px; color: #666; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #f1f5f9; text-align: left; padding: 12px; border-bottom: 2px solid #e2e8f0; font-size: 12px; text-transform: uppercase; color: #64748b; }
            td { padding: 12px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }
            .store-name { font-weight: bold; font-size: 14px; }
            .date { font-size: 12px; color: #666; margin-top: 4px; }
            .badges { display: flex; flex-direction: column; gap: 4px; font-size: 10px; }
            .badge { padding: 2px 6px; border-radius: 4px; font-weight: bold; width: fit-content; }
            .safe { background-color: #d1fae5; color: #065f46; }
            .caution { background-color: #fef3c7; color: #92400e; }
            .avoid { background-color: #fee2e2; color: #991b1b; }
            .footer { margin-top: 40px; text-align: center; font-size: 10px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <h1>Shopping History Report</h1>
          <div class="summary">Generated on ${new Date().toLocaleDateString()}</div>
          
          <table>
            <thead>
              <tr>
                <th>Store & Date</th>
                <th style="text-align: center;">Items</th>
                <th>Health Breakdown</th>
              </tr>
            </thead>
            <tbody>
              ${rows}
            </tbody>
          </table>

          <div class="footer">
            Report generated by CartGenie (SW Engineering Final Project) | Total Receipts: ${historyItems.length}
          </div>
        </body>
      </html>
    `;
  };

  // 📌 פונקציה שמפעילה את יצירת ה-PDF והשיתוף
  const handleExportPDF = async () => {
    if (historyItems.length === 0) {
      Alert.alert('No Data', 'There is no history to export.');
      return;
    }

    setIsGeneratingPdf(true);
    try {
      // 1. צור את ה-HTML
      const html = generateHtml();

      // 2. צור קובץ PDF
      const { uri } = await Print.printToFileAsync({ html });
      console.log('PDF generated at:', uri);

      // 3. שתף את הקובץ
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      Alert.alert('Error', 'Failed to generate PDF report.');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleDelete = (itemId: string) => {
    Alert.alert("Delete Receipt", "Are you sure?", [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Delete", 
          style: "destructive", 
          onPress: async () => {
            try {
              const res = await fetch(`${API_URL}/api/history/${itemId}`, { method: 'DELETE' });
              const data = await res.json();
              if (data.success) {
                setHistoryItems(prev => prev.filter(item => item._id !== itemId));
              }
            } catch (error) { console.error(error); }
          }
        }
      ]
    );
  };

  const renderItem = ({ item }: { item: ReceiptHistoryItem }) => {
    const date = new Date(item.scanDate);
    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
            <View style={styles.storeContainer}>
                <View style={styles.iconBox}>
                    <Ionicons name="receipt-outline" size={20} color="#fff" />
                </View>
                <View>
                    <Text style={styles.storeName}>{item.storeName || 'Unknown Store'}</Text>
                    <Text style={styles.dateText}>
                        {date.toLocaleDateString()} • {date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </Text>
                </View>
            </View>
            <TouchableOpacity onPress={() => handleDelete(item._id)} style={styles.deleteBtn}>
                <Ionicons name="trash-outline" size={18} color="#94A3B8" />
            </TouchableOpacity>
        </View>

        <View style={styles.divider} />

        <View style={styles.summaryContainer}>
            <Text style={styles.itemCountText}>{item.itemCount} Items Scanned</Text>
            <View style={styles.healthStats}>
                {/* (שמרתי את אותו קוד שלך כאן) */}
                {item.healthSummary.safe > 0 && <View style={[styles.statBadge, { backgroundColor: '#D1FAE5' }]}><Text style={[styles.statText, { color: '#065F46' }]}>✓ {item.healthSummary.safe}</Text></View>}
                {item.healthSummary.caution > 0 && <View style={[styles.statBadge, { backgroundColor: '#FEF3C7' }]}><Text style={[styles.statText, { color: '#92400E' }]}>! {item.healthSummary.caution}</Text></View>}
                {item.healthSummary.avoid > 0 && <View style={[styles.statBadge, { backgroundColor: '#FEE2E2' }]}><Text style={[styles.statText, { color: '#991B1B' }]}>✕ {item.healthSummary.avoid}</Text></View>}
            </View>
        </View>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      {/* 📌 כותרת עליונה עם כפתור ייצוא */}
      <View style={styles.headerRow}>
        <Text style={styles.headerTitle}>History</Text>
        <TouchableOpacity 
            style={[styles.exportBtn, historyItems.length === 0 && { opacity: 0.5 }]} 
            onPress={handleExportPDF}
            disabled={isGeneratingPdf || historyItems.length === 0}
        >
            {isGeneratingPdf ? (
                <ActivityIndicator size="small" color="#fff" />
            ) : (
                <>
                    <Ionicons name="share-outline" size={18} color="#fff" />
                    <Text style={styles.exportText}>Export PDF</Text>
                </>
            )}
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.centerContainer}><ActivityIndicator size="large" color="#0096c7" /></View>
      ) : (
        <FlatList
          data={historyItems}
          keyExtractor={(item) => item._id}
          renderItem={renderItem}
          contentContainerStyle={styles.listContent}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetchReceipts(); }} />}
          ListEmptyComponent={
            <View style={styles.emptyContainer}>
              <Ionicons name="document-text-outline" size={60} color="#CBD5E1" />
              <Text style={styles.emptyTitle}>No Receipts</Text>
            </View>
          }
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  // 📌 עיצוב חדש לכותרת העליונה
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9'
  },
  headerTitle: { fontSize: 22, fontWeight: 'bold', color: '#0F172A' },
  exportBtn: {
    flexDirection: 'row',
    backgroundColor: '#0096c7',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    gap: 6
  },
  exportText: { color: '#fff', fontWeight: '600', fontSize: 14 },

  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  listContent: { padding: 16, paddingBottom: 40 },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 16, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 3 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  storeContainer: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  iconBox: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#334155', justifyContent: 'center', alignItems: 'center' },
  storeName: { fontSize: 16, fontWeight: '700', color: '#0F172A' },
  dateText: { fontSize: 12, color: '#64748B', marginTop: 2 },
  deleteBtn: { padding: 4 },
  divider: { height: 1, backgroundColor: '#F1F5F9', marginBottom: 12 },
  summaryContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  itemCountText: { fontSize: 13, color: '#64748B', fontWeight: '500' },
  healthStats: { flexDirection: 'row', gap: 8 },
  statBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, gap: 4 },
  statText: { fontSize: 12, fontWeight: '700' },
  emptyContainer: { alignItems: 'center', marginTop: 80 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#334155', marginTop: 16 },
});